# -*- coding: utf-8 -*-
"""Profitability_Ratios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xPG2Q5jgW-WvQBLzh8faZl-8oNdp9MCr
"""

import pandas as pd

import numpy as np

import statsmodels.api as sm

# Örnek veri

data = {
    'karlılık_oranı': [10, 12, 15, 18, 20],
    'faiz_oranı': [5, 4, 3, 2, 1],
    'ekonomik_büyüme': [3, 4, 5, 6, 7]
}
df = pd.DataFrame(data)

# Bağımsız değişkenler ve bağımlı değişken

X = df[['faiz_oranı', 'ekonomik_büyüme']]
y = df['karlılık_oranı']

# Sabit terimi (bias) ekleyerek modeli oluşturma

X = sm.add_constant(X)

# Modeli oluşturma

model = sm.OLS(y, X).fit()

# Model özetini yazdırma

print(model.summary())

# Modeli görselleştirmek için;

import matplotlib.pyplot as plt

# Tahminleri al

predictions = model.predict(X)

# Gerçek ve tahmini karlılık oranlarını birleştir

results = pd.DataFrame({'Gerçek': y,
'Tahmin': predictions})

# Grafiği çizdir

plt.figure(figsize=(10, 6))
plt.plot(results['Gerçek'],
label='Gerçek')
plt.plot(results['Tahmin'],
label='Tahmin')
plt.title('Karlılık Oranları - Gerçek vs. Tahmin')
plt.xlabel('Gözlem Numarası')
plt.ylabel('Karlılık Oranı')
plt.legend()
plt.show()